disabled_rules: 
  - control_statement
  - discarded_notification_center_observer
  - large_tuple
  - multiple_closures_with_trailing_closure
  - function_body_length
excluded: 
  - Pods
  - Localize.swift
  - Ressources
opt_in_rules:
  - empty_count
  - empty_string
reporter: xcode
function_parameter_count:
  warning: 8
  error: 10
file_length: 
  warning: 600
  error: 800
  ignore_comment_only_lines: true
force_cast: warning
force_try: 
  severity: warning
line_length:
  warning: 175
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
type_body_length: 
  - 300
  - 400
identifier_name:
  allowed_symbols: "_"
  max_length:
    warning: 40
    error: 50
  min_length:
    warning: 2
    error: 1
  excluded:
    - iPhone
    - id
    - url
    - db
    - i
    - y
    - x
    - a
    - b
    - c
    - r
    - u
cyclomatic_complexity:
    warning: 15
    error: 25 
type_name: 
  excluded: 
    - iPhone
    - id
    - url
    - db
  max_length: 
    error: 55
    warning: 50
  min_length: 2
custom_rules:
  disable_nslog:
    included: ".*\\.swift"
    name: "NSLog"
    regex: "((\\bNSLog))\\s*\\("
    message: "NSLog prohibited"
    severity: error
